baseURL = "https://www.xxxlbox.com"
languageCode = "zh-cn"
DefaultContentLanguage = "zh"
title = "Track3's Blog"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
hasCJKLanguage = true

[blackfriday]
hrefTargetBlank = true

[author]
  name = "Track3"

[taxonomies]
  tag = "tags"
  category = ""

[params]
  author = "Track3"

  dateform       = "Jan 02, 2006"
  dateformFull   = "2006-01-02 15:04"
  dateformList   = "Jan 2"
  dateformSingle = "Mon, Jan 2"

[[params.mainMenu]]
  link = "/posts/"
  text = "Posts"

[[params.mainMenu]]
  link = "/friends/"
  text = "Friends"

[[params.mainMenu]]
  link = "/about/"
  text = "About"
