baseURL = "https://ojbk.im"
languageCode = "zh-hans"
title = "Track3's Blog"
staticDir = ["static", "content-static"]

hasCJKLanguage = true
rssLimit = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
googleAnalytics = "UA-125057333-1"

[author]
  name = "Track3"

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    noClasses = false

  [markup.blackFriday]
    hrefTargetBlank = true

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 02"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  accentColor = "#54BAB9"
  images = ["apple-touch-icon.png"]
  # bgImg = "/img/bg.jpg"

  gitUrl = "https://github.com/Track3/blog/commit/"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/ThatTrack3"

  [[params.social]]
    name = "telegram"
    url = "http://t.me/ThatTrack3"

  [[params.social]]
    name = "github"
    url = "https://github.com/Track3"

[menu]

  [[menu.main]]
    name = "Writing"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    name = "Friends"
    url = "/friends/"
    weight = 30

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 40
