baseURL = "https://www.xxxlbox.com"
languageCode = "zh-hans"
title = "Track3's Blog"

enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
hasCJKLanguage = true
rssLimit = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
googleAnalytics = "UA-125057333-1"

[author]
  name = "Track3"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag = "tags"
  category = ""

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  gitUrl = "https://github.com/Track3/blog/commit/"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/ThatTrack3"

  [[params.social]]
    name = "telegram"
    url = "http://t.me/ThatTrack3"

  [[params.social]]
    name = "github"
    url = "https://github.com/Track3"

[menu]

  [[menu.main]]
    name = "Writing"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    name = "Friends"
    url = "/friends/"
    weight = 20

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30
